api:
  port: ":3000"
  version: "v1.1.1"
parser:
  default_route: "https://journal.tinkoff.ru"

queue:
  ip: "192.168.232.135"
  username: "rabbitmq"
  password: "8w5OraD5ea!Q"

search-engine:
  ip: "192.168.232.135"
  port: "9200"